### ISSUE TITLE
Wrong paths when compiling

### ISSUE THREAD

**Issue by sbeyer** [copperspice/doxypress#14]
I cannot get current master (e9a4dbe) to compile.

Using autoreconf, ./configure, make, the binaries `lrelease`, `rcc` and alike cannot be found because they are expected in `${CS_HOME}/bin` (which is my `$HOME/bin`) instead of `/usr/bin` ... After fixing that, I have the same problem with the Qt include paths, i.e. it cannot find the `QString` header file.

Using CMake, a lot of Windows paths (starting with drives z: and c:) are hard-coded.

**Comment by agserm** [comment]
Thanks for your question.

First of all, which platform are you building on? Also, you mention the Qt include path. Are you trying to build DoxyPress with Qt? Just for reference, DoxyPress uses the CopperSpice library, not Qt.

You mention that you "fixed" something in reference to CS_HOME. Can you elaborate? CS_HOME should be set to the root of an installed version of CopperSpice.

The CMake builds are a work in progress at this time. Autotools is the only supported build system at the moment.

**Comment by sbeyer** [comment]
Oh, that's the problem then 🤦‍ I took the trial-and-error approach and `lrelease`, `rcc`, `#include <QString>` are so tyical Qt things that I didn't think about something else.
