### ISSUE TITLE
Doxypress documentation site is down

### ISSUE THREAD

**Issue by banagale** [copperspice/doxypress#15]
The [official documentation page](http://www.copperspice.com/documentation-doxypress.html) for doxypress seems offline.

**Comment by agserm** [comment]
Thank you so much for noticing this and letting us know. We had an error on our hosting system which our monitoring did not catch. The affected server has been restarted and our monitoring has been improved to catch future issues of this type.

**Comment by banagale** [comment]
Glad to hear this. Thank you for your efforts.
