### ISSUE TITLE
macOS: symlink to the command-line version in /usr/local/bin

### ISSUE THREAD

**Issue by rwols** [copperspice/doxypress#19]
The installation process of the GUI should make a symlink in `/usr/local/bin` to the command-line executable. e.g. something like this

```
$ ln -s /Applications/DoxyPressApp.app/Contents/MacOS/doxypress /usr/local/bin/doxypress
```

**Comment by bgeller** [comment]
This is something we need to investigate further since we actually do not use an installer.  We would welcome your input and even a pull request if possible.

**Comment by agserm** [comment]
I have not found any current examples for this use case in the developer documentation.

Please feel free to reopen this ticket if you can find an example of how this should be done according to the Apple guidelines.
