### ISSUE TITLE
xml schema violated by name change

### ISSUE THREAD

**Issue by purpleKarrot** [copperspice/doxypress#2]
The XML schema defines the element `doxygenindex` here: https://github.com/copperspice/doxypress/blob/master/resources/xml/index.xsd#L3

The XML generator actually writes `doxypressindex`: https://github.com/copperspice/doxypress/blob/master/src/xmlgen.cpp#L2112

Either change the schema to reflect the code change, or fix the code and keep the schema as is.
The latter option is preferred, as it keeps compatibility existing tools that consume doxygen generated XML.

**Comment by bgeller** [comment]
We have changed the XML schema.
