### ISSUE TITLE
No tags in git and not releases on github

### ISSUE THREAD

**Issue by otopetrik** [copperspice/doxypress#31]
There are no [tags](https://github.com/copperspice/doxypress/tags) in the git repository.
(also no GitHub's [releases](https://github.com/copperspice/doxypress/releases))

On the forum, there are already announcements of multiple released [versions](https://forum.copperspice.com/viewforum.php?f=6).
At least one is already available in both [source](https://download.copperspice.com/doxypress/) and [binary](https://download.copperspice.com/doxypress/binary/) forms (did not find older versions).

The lack of tags makes it look like there are no releases yet!
(and no [releases](https://github.com/copperspice/doxypress/releases) results in GitHub's "Watch releases" functionality not notifiying about new versions)

Is it possible to tag the latest version (and all the future ones) ?

**Comment by agserm** [comment]
Thank you for your request. This has been completed.
