### ISSUE TITLE
Brief descriptions are duplicated when using clang parser

### ISSUE THREAD

**Issue by planetmarshall** [copperspice/doxypress#37]
Using 

 * Ubuntu 18.04 LTS
 * doxypress 1.3.8 binary release
 * Clang-9

## Steps to reproduce

```
git clone https://github.com/planetmarshall/doxypress_test
cd doxypress_test
mkdir build
cmake -B build
doxypress doxypress.json
```

## Expected results

Generates the following html in `doc/html/namespacelib.html`

```
<p>Create an empty array. </p>
<p>Create an empty array and return it </p>
```

## Actual results

The following HTML is generated, with a duplicated brief description
```
<p>Create an empty array. </p>
<p>Create an empty array</p>
<p>Create an empty array and return it </p>

```

### Workaround

Set `"clang-parsing": false` in `doxypress.json`

**Comment by bgeller** [comment]
Can you let us know the tag settings for "Repeat brief description",  "JavaDoc auto brief", and "Qt-Style auto brief".  It sounds like you have some conflicting settings.  This is not a clang parsing issue.

**Comment by agserm** [comment]
Closing due to no response, feel free to reopen with additional information.
