### ISSUE TITLE
Overloaded function (with templates as change) is not displayed in html page

### ISSUE THREAD

**Issue by zchrissirhcz** [copperspice/doxypress#46]
I was using doxygen and failed to get function properly displayed ( https://github.com/doxygen/doxygen/issues/8921 ), thus I search and find doxypress.

Sadly, doxypress 1.4.1 also failed to parse the same functions, only get one `hello()` displayed in the html page:
```c++
#pragma once

void hello(const char* name);


template<typename T>
void hello(const char* name);
```

The json file I am using is in [what.tar.gz](https://github.com/copperspice/doxypress/files/7618917/what.tar.gz) .

**Comment by zchrissirhcz** [comment]
![图片](https://user-images.githubusercontent.com/3831847/143889181-496c91ca-93c5-4fe7-8882-c9c4dc1182d8.png)

**Comment by zchrissirhcz** [comment]
![图片](https://user-images.githubusercontent.com/3831847/143889360-9c47cb3b-79bc-4ece-9385-393c222832bf.png)

**Comment by agserm** [comment]
We have confirmed that when you have a free function overloaded with a template function, the documentation for both is merged into the non-template function. We are investigating the issue. Thank you for reporting this with a test case.
