### ISSUE TITLE
Concepts (c++20) support

### ISSUE THREAD

**Issue by milasudril** [copperspice/doxypress#50]
Does doxypress support c++20 concepts?

**Comment by agserm** [comment]
There are two different parsing modes in DoxyPress. The lex parser is used by default. As an alternative you can specify the built in clang parser which is better at handling more complex declarations. We believe the clang parser does a slightly better job at parsing concepts and requires clauses.  

Both parsers fully support concepts for HTML output. If you are using a different output format concepts may not be documented in as much detail. If you experience any issues please provide a small sample and we will escalate this as quickly as possible.
