### ISSUE TITLE
The collectors/collect tags isn't self-explanatory

### ISSUE THREAD

**Issue by Joebeazelman** [copperspice/doxypress#56]
**Collectors/Collect** project tags make no sense. They all appear to be toolchain flags which are confirmed in the discovery and documentation. The tag should be renamed to something self-explanatory. What do Collectors mean?  What is being "collected"?  Do you really "collect" flags?  I guess it wouldn't make sense to use options, since they are categorically different from internal tools. Why not use "Toolchains/Flags", or something similar?

**Comment by bgeller** [comment]
Was this issue meant for this project?  DoxyPress is an application which is used to generate source code documentation.  We do not have anything in the code base which refers to a tool chain flag.

**Comment by Joebeazelman** [comment]
Oops. I didn't state the context. I referring to the markup used in the **project.xml** file.

**Comment by bgeller** [comment]
DoxyPress does not have a "project.xml" file as part of the source code. Could this file be part of some other project you are using?

**Comment by salkinium** [comment]
Just FYI, this issue was in reference to [lbuild collectors](https://github.com/modm-io/lbuild#collectors).
