### ISSUE TITLE
C# Property default values applied incorrectly

### ISSUE THREAD

**Issue by TransientResponse** [copperspice/doxypress#6]
This is an [issue](https://bugzilla.gnome.org/show_bug.cgi?id=759190) that's been in Doxygen for a while, and since so much work is being done on the codebase, I'd like to help finally fix it. Unfortunately with the rewrite to scanner.l (to commentscan.l, I believe) the previously identified line numbers are no longer valid and some quick searching for variables has failed. If someone with more experience in the codebase could direct me to where C# properties are parsed, I would be happy to try and fix this.

**Comment by agserm** [comment]
We are very happy to report we found the problem with C# property default values.

We are rebuilding our CI machine this weekend for increased performance, it should be up in a day or two so we can release and push to github by this weekend. 

Sorry it took a while to address this issue, Barbara had a total knee replacement in June and we both resumed work on the project in November. It was great to get back to everything and finally have a chance to look at this issue as we catch up.

**Comment by TransientResponse** [comment]
I'm so glad to hear this. I'm eagerly awaiting your next binary release (stuck on Windows) so I can start using DoxyPress in production.

**Comment by agserm** [comment]
Are you on Windows 64-bit or 32-bit? We would be happy to provide a release candidate for you to test in the next few days.

**Comment by TransientResponse** [comment]
I'm on Windows x64, and would be very grateful for a test build.

**Comment by agserm** [comment]
We have released DoxyPress 1.2.5, which has the resolution for this issue. Please give it a try and let us know how it works for you.

http://download.copperspice.com/doxypress/binary/

**Comment by TransientResponse** [comment]
Got it, the issue I had was fixed, but I discovered another issue along the way. Will be posting it separately.

**Comment by agserm** [comment]
Thanks for your bug report and for verifying the resolution. We will look at your new issue next week.
