### ISSUE TITLE
LaTeX output problems

### ISSUE THREAD

**Issue by TransientResponse** [copperspice/doxypress#7]
I've found a few issues with the LaTeX output produced by Doxypress. The main file `refman.tex` has a fairly perplexing line `remove-value`, under the comment "NLS Support Packages". I don't know the purpose of it, as Doxygen's output does not have this line. Commenting it out has no ill effects, and in fact removes extraneous (almost) blank pages from the resulting PDF. 

The bigger problem, however, is in the individual class/function documention `tex` files: the description text of function parameters are not applied in the tex file. 

Compare this example output produced by Doxypress:

    \begin{DoxyParams}{Parameters}
    {\em num} & 
    
    \\
    \hline
    \end{DoxyParams}
    \begin{DoxyReturn}{Returns}
    An uint16\+\_\+t. 
    \end{DoxyReturn}

To this output (from the same source) by Doxygen:

    \begin{DoxyParams}{Parameters}
    {\em num} & A number.\\
    \hline
    \end{DoxyParams}
    \begin{DoxyReturn}{Returns}
    An uint16\+\_\+t. 
    \end{DoxyReturn}

Also, Doxypress output is missing the `make.bat` file to build the latex on Windows. 
Simply copying this file from Doxygen appears to work without issue once the `remove-value` line is commented out. 

C++ code used for this example is below. 

`example.h`:

    #pragma once

    class Test
    {
        public:
        uint16_t swap16(uint16_t);
    }; 

`example.cpp`:

    #include "example.h"

    /**
    * Swap 16.
    *
    * @param num A number.
    *
    * @returns An uint16_t.
    **/
    uint16_t Test::swap16(uint16_t num)
    {
        return (num >> 8) | (num << 8);
    }

**Comment by TransientResponse** [comment]
Update: upon testing 1.2.4, function parameters are now properly documented. 

However make.bat is still missing and the mysterious `remove-value` line is still present. Copy-paste make.bat from a doxygen project and comment out the `remove-value` in refman.tex and all is well in the output PDF.

**Comment by agserm** [comment]
The make.bat and remove-value issues have been found and corrected. We have pushed the fix to github and both items will be resolved in the next release of DoxyPress. Thank you for your feedback and diligence in testing.
