### ISSUE TITLE
Incorrect HHP generation

### ISSUE THREAD

**Issue by TransientResponse** [copperspice/doxypress#8]
When generating HTML output for CHM files, the HHP file has incorrect referencing for internal images such as class hierarchy diagrams; the HHP file lists them as `html\file.png`. This is incorrect, as the images are not in an `html` subdirectory. All HTML output files are placed in the same directory as the HHP. 

The simple solution is simply to remove `html\` prefix from the offending lines.

**Comment by TransientResponse** [comment]
Just tested 1.2.4, and this issue is fixed. I'm marking it closed.

**Comment by TransientResponse** [comment]
1.2.9 has regressed; images are now listed in the HHP as `html/file.png`. 

I have not tested 1.2.6/7/8. 1.2.5's output was fine as I recall.

**Comment by agserm** [comment]
When you closed this issue, there had been no changes to code that might have affected the HHP file. We will take another look and see if this can be reproduced.

**Comment by agserm** [comment]
Thanks for this report. We have been able to reproduce and resolve the issue. The code will be pushed to GitHub later today, and will be in the next version of DoxyPress which should be released in the next two weeks.

**Comment by TransientResponse** [comment]
Wow, I really thought it had been fixed at 1.2.4. I must have somehow tricked myself. Regardless, thanks for your quick attention.

**Comment by TransientResponse** [comment]
This is still an issue 1.2.10; class diagrams are being listed as e.g.
```
[FILES]
tab_a.png
tab_b.png
tab_h.png
tab_s.png
nav_h.png
nav_f.png
bc_s.png
doxypress.png
closed.png
open.png
bdwn.png
sync_on.png
sync_off.png
class_advanced_illumination_1_1_d_c_s__100
class_advanced_illumination_1_1_disconnect_event_args
class_advanced_illumination_1_1_error_event_args
class_advanced_illumination_1_1_fault_event_args
class_advanced_illumination_1_1_warning_event_args
```
I believe the class lines should be listed as .png as well? I get the following output from the HTML Help Compiler:

```
Microsoft HTML Help Compiler 4.74.8702

Compiling c:\Users\[redacted]\DCS100\doc\html\DCS100.chm

HHC5003: Error: Compilation failed while compiling class_advanced_illumination_1_1_d_c_s__100.
HHC5003: Error: Compilation failed while compiling class_advanced_illumination_1_1_disconnect_event_args.
HHC5003: Error: Compilation failed while compiling class_advanced_illumination_1_1_error_event_args.
HHC5003: Error: Compilation failed while compiling class_advanced_illumination_1_1_fault_event_args.
HHC5003: Error: Compilation failed while compiling class_advanced_illumination_1_1_warning_event_args.


The following files were not compiled:
class_advanced_illumination_1_1_d_c_s__100
class_advanced_illumination_1_1_disconnect_event_args
class_advanced_illumination_1_1_error_event_args
class_advanced_illumination_1_1_fault_event_args
class_advanced_illumination_1_1_warning_event_args
```

Strangely enough, it still generates the CHM file and everything appears normal, inheritance diagrams included. Adding `.png` to the class files removes the errors from CHM compilation.

**Comment by agserm** [comment]
Thanks for testing, sorry we missed this the first time around. We have just pushed the fix and it will be in the next release of DoxyPress.
